### ISSUE TITLE
it's worse than react-native-background-timer

### ISSUE THREAD

**Issue by muammeralkis** [juanamd/react-native-background-timer-android#1]
yes, it is not working on lock screen after 1 minute. react-native-background-timer had more minutes for it

**Comment by juanamd** [comment]
I've been using this library in production for more than a year on thousands of devices and multiple apps and this has not been my experience.
If you have a reproducible demo or a specific device or use case where the issue that you describe is present I will be willing to investigate. Otherwise, continue using the original version if that "gives you more minutes" or whatever.
